### ISSUE TITLE
MM Link Voice Pak issues.

### ISSUE THREAD

**Issue by SnowyHuskybutt** [hylian-modding/Z64-CustomPlayerModels#80] opened 2021-03-22 11:08 UTC
Hey there!

Just wanted to report some bugs with the MM Link mod. When playing with a friend they've reported that the voice itself doesn't have any distancing at all no matter where the player is in the world causing the voice to sound incredibly loud to other users which can be quite distracting.

Upon exiting a Grotto both the MM Voice Files + OOT Voice Files will play together and overlap each other, I'm unsure what causes this but it's consistent upon entering/exiting grottos.

Hoping both issues may be able to be fixed for the voice pack!

**Comment by denoflionsx** [comment] 2021-03-29 05:33
The voices do have distancing and should be playing based on 3d world position.

The grotto issue is known and fixed in the next OotO update.

**Comment by SnowyHuskybutt** [comment] 2021-04-02 04:31
Huh okay then, my friend mentioned the voice broke for them and was super loud as if I was always right next to them.

Another bug I've noticed while playing is Adult Link's falling yell when falling from high heights doesn't cut off at all when he hits the ground or grabs ledges, the sound file still plays in full when it should be getting cut off if he takes damage or grabs a ledge, also when underwater his voice isn't muffled and garbled like it's meant to be either, thought I'd mention those two to see if they're fixable.

Glad to hear the grotto issue is being fixed though in the next update!

UPDATE: I recently managed to find the 3 unique injury sounds for Fierce Deity Link that I noticed haven't been provided anywhere for download and are completely different to OOT Adult Link's sounds upon being hit normally. Would you like me to provide them so they can be included within the pak?

**Comment by SnowyHuskybutt** [comment] 2021-05-15 05:39
BUMP.

Noticed the pak was updated recently and still has issues present.

- Fall sounds play fully regardless of impact with the ground when they should cut off. Affects both Young Link and Adult Link.
- Adult Link missing unique MM Injury Sounds upon being hurt normally.
- Adult Link knockdown sound volume much lower then overall sounds, hard to hear over music.
- Adult Link underwater sounds are not muffled like intended.
- Young Link Voice quieter then music volume, gets drowned out easily.

**Comment by denoflionsx** [comment] 2021-05-15 08:02
The falling isn't unique to that voice pak. The voice pak system only knows
what to play becsuse Link's actor says play this. There is no subsequent
stop. It plays all sounds to completion unless the same sound interrupts
itself.

So, basically, that is intended behavior and not a bug.

**Comment by denoflionsx** [comment] 2021-05-15 08:06
Also no voice pak supports underwater muffling and probably never will.
We're playing the sounds outside the game and implementing a muffle filter
over the ogg sound stream isn't something I'd do for performance reasons.

**Comment by denoflionsx** [comment] 2021-05-15 08:11
Volume issues or whatever should be reported to whoever made the pak. You
don't report to the librarian when a book has a typo in it. Those with
issue ticket access here have nothing to do with the actual content, we
just organize and preserve it.

**Closed as completed** 2021-07-18 04:43 UTC
Labels: bug
